techpack: video: Add firmware buffer requirement property
it is required for SM8150 otherwise firmware returns SYS_ERROR

Fix following error:
HFI_EVENT_SYS_ERROR: 1, 0x2b474